/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as ShortlistRouteImport } from './routes/shortlist'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ReportAbuseRouteImport } from './routes/report-abuse'
import { Route as PressRouteImport } from './routes/press'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialYoutubeRouteImport } from './routes/social.youtube'
import { Route as SocialTwitterRouteImport } from './routes/social.twitter'
import { Route as SocialInstagramRouteImport } from './routes/social.instagram'
import { Route as SocialFacebookRouteImport } from './routes/social.facebook'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileCreateRouteImport } from './routes/profile.create'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'

const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistRoute = ShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAbuseRoute = ReportAbuseRouteImport.update({
  id: '/report-abuse',
  path: '/report-abuse',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialYoutubeRoute = SocialYoutubeRouteImport.update({
  id: '/social/youtube',
  path: '/social/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialTwitterRoute = SocialTwitterRouteImport.update({
  id: '/social/twitter',
  path: '/social/twitter',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialInstagramRoute = SocialInstagramRouteImport.update({
  id: '/social/instagram',
  path: '/social/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialFacebookRoute = SocialFacebookRouteImport.update({
  id: '/social/facebook',
  path: '/social/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCreateRoute = ProfileCreateRouteImport.update({
  id: '/profile/create',
  path: '/profile/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/careers': typeof CareersRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/interests': typeof InterestsRoute
  '/membership': typeof MembershipRoute
  '/notifications': typeof NotificationsRoute
  '/press': typeof PressRoute
  '/report-abuse': typeof ReportAbuseRoute
  '/safety': typeof SafetyRoute
  '/shortlist': typeof ShortlistRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/create': typeof ProfileCreateRoute
  '/profile/edit': typeof ProfileEditRoute
  '/social/facebook': typeof SocialFacebookRoute
  '/social/instagram': typeof SocialInstagramRoute
  '/social/twitter': typeof SocialTwitterRoute
  '/social/youtube': typeof SocialYoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/careers': typeof CareersRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/interests': typeof InterestsRoute
  '/membership': typeof MembershipRoute
  '/notifications': typeof NotificationsRoute
  '/press': typeof PressRoute
  '/report-abuse': typeof ReportAbuseRoute
  '/safety': typeof SafetyRoute
  '/shortlist': typeof ShortlistRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/create': typeof ProfileCreateRoute
  '/profile/edit': typeof ProfileEditRoute
  '/social/facebook': typeof SocialFacebookRoute
  '/social/instagram': typeof SocialInstagramRoute
  '/social/twitter': typeof SocialTwitterRoute
  '/social/youtube': typeof SocialYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/careers': typeof CareersRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/interests': typeof InterestsRoute
  '/membership': typeof MembershipRoute
  '/notifications': typeof NotificationsRoute
  '/press': typeof PressRoute
  '/report-abuse': typeof ReportAbuseRoute
  '/safety': typeof SafetyRoute
  '/shortlist': typeof ShortlistRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/create': typeof ProfileCreateRoute
  '/profile/edit': typeof ProfileEditRoute
  '/social/facebook': typeof SocialFacebookRoute
  '/social/instagram': typeof SocialInstagramRoute
  '/social/twitter': typeof SocialTwitterRoute
  '/social/youtube': typeof SocialYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/careers'
    | '/chat'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/interests'
    | '/membership'
    | '/notifications'
    | '/press'
    | '/report-abuse'
    | '/safety'
    | '/shortlist'
    | '/success-stories'
    | '/auth/forgot-password'
    | '/auth/register'
    | '/auth/sign-in'
    | '/auth/verify-otp'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/profile/$id'
    | '/profile/create'
    | '/profile/edit'
    | '/social/facebook'
    | '/social/instagram'
    | '/social/twitter'
    | '/social/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/careers'
    | '/chat'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/interests'
    | '/membership'
    | '/notifications'
    | '/press'
    | '/report-abuse'
    | '/safety'
    | '/shortlist'
    | '/success-stories'
    | '/auth/forgot-password'
    | '/auth/register'
    | '/auth/sign-in'
    | '/auth/verify-otp'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/profile/$id'
    | '/profile/create'
    | '/profile/edit'
    | '/social/facebook'
    | '/social/instagram'
    | '/social/twitter'
    | '/social/youtube'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/careers'
    | '/chat'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/interests'
    | '/membership'
    | '/notifications'
    | '/press'
    | '/report-abuse'
    | '/safety'
    | '/shortlist'
    | '/success-stories'
    | '/auth/forgot-password'
    | '/auth/register'
    | '/auth/sign-in'
    | '/auth/verify-otp'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/profile/$id'
    | '/profile/create'
    | '/profile/edit'
    | '/social/facebook'
    | '/social/instagram'
    | '/social/twitter'
    | '/social/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  CareersRoute: typeof CareersRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  InterestsRoute: typeof InterestsRoute
  MembershipRoute: typeof MembershipRoute
  NotificationsRoute: typeof NotificationsRoute
  PressRoute: typeof PressRoute
  ReportAbuseRoute: typeof ReportAbuseRoute
  SafetyRoute: typeof SafetyRoute
  ShortlistRoute: typeof ShortlistRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileCreateRoute: typeof ProfileCreateRoute
  ProfileEditRoute: typeof ProfileEditRoute
  SocialFacebookRoute: typeof SocialFacebookRoute
  SocialInstagramRoute: typeof SocialInstagramRoute
  SocialTwitterRoute: typeof SocialTwitterRoute
  SocialYoutubeRoute: typeof SocialYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist': {
      id: '/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof ShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-abuse': {
      id: '/report-abuse'
      path: '/report-abuse'
      fullPath: '/report-abuse'
      preLoaderRoute: typeof ReportAbuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/youtube': {
      id: '/social/youtube'
      path: '/social/youtube'
      fullPath: '/social/youtube'
      preLoaderRoute: typeof SocialYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/twitter': {
      id: '/social/twitter'
      path: '/social/twitter'
      fullPath: '/social/twitter'
      preLoaderRoute: typeof SocialTwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/instagram': {
      id: '/social/instagram'
      path: '/social/instagram'
      fullPath: '/social/instagram'
      preLoaderRoute: typeof SocialInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/facebook': {
      id: '/social/facebook'
      path: '/social/facebook'
      fullPath: '/social/facebook'
      preLoaderRoute: typeof SocialFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/create': {
      id: '/profile/create'
      path: '/profile/create'
      fullPath: '/profile/create'
      preLoaderRoute: typeof ProfileCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  CareersRoute: CareersRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  InterestsRoute: InterestsRoute,
  MembershipRoute: MembershipRoute,
  NotificationsRoute: NotificationsRoute,
  PressRoute: PressRoute,
  ReportAbuseRoute: ReportAbuseRoute,
  SafetyRoute: SafetyRoute,
  ShortlistRoute: ShortlistRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProfileCreateRoute: ProfileCreateRoute,
  ProfileEditRoute: ProfileEditRoute,
  SocialFacebookRoute: SocialFacebookRoute,
  SocialInstagramRoute: SocialInstagramRoute,
  SocialTwitterRoute: SocialTwitterRoute,
  SocialYoutubeRoute: SocialYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
